backend:
  name: git-gateway
  branch: netlify-cms # Branch to update (optional; defaults to master)

# media_folder: "static/uploads" # where files are saved
# public_folder: "/static/uploads" # public url from dist

media_library:
  name: cloudinary
  config: 
    cloud_name: evv
    api_key: 858462229676913

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "static/content/home.json"
        fields: 
          - label: 'Sections'
            name: 'sections'
            widget: list
            types:
              - label: 'Image'
                name: 'image'
                widget: object
                # summary: '{{fields.image}}'
                fields: 
                  - label: Image
                    name: image
                    widget: image
                    media_library: 
                      config: 
                        multiple: false
                  - {label: Alt, name: alt, widget: string, default: (Describe the image for the visually impaired!) }
              - label: 'Video'
                name: 'video'
                widget: object
                fields:
                  - label: Video
                    name: video_lnd
                    widget: file
                    media_library:
                      config:
                        multiple: false
                  # - label: Portrait Video
                  #   name: video_mbl
                  #   widget: file
                  #   media_library:
                  #     config:
                  #       multiple: false
    # files:
    #   - label: "Home"
    #     name: "home"
    #     file: "static/content/home.json"
    #     fields: 
    #       - {label: Title, name: title, widget: string}
    #       - label: Sections
    #         name: sections
    #         widget: list
    #         fields: 
    #           - {label: Image, name: image, widget: image}
    #           - {label: Vimeo URL, name: video, widget: string, required: false}
