backend:
  name: git-gateway
  branch: netlify-cms # Branch to update (optional; defaults to master)

media_folder: "static/uploads" # where files are saved
public_folder: "/static/uploads" # public url from dist

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "static/content/home.json"
        fields: 
          - {label: Title, name: title, widget: string}
          - label: Sections
            name: sections
            widget: list
            fields: 
              - {label: Image, name: image, widget: image}
              - {label: Video URL, name: video, widget: string}
